import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./NavBar";
import QueryClientProvider from "./QueryClientProvider";
import "./globals.css";

import "./theme-config.css";
import AuthProvider from "./(home)/auth/Provider";
import { ProjectContextProvider } from "./(home)/hooks/useProjectContext";
import { IssueContextProvider } from "./(home)/hooks/useIssueContext";
import { TimerContextProvider } from "./(home)/hooks/useTimerContext";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <body className={inter.variable}>
        <AuthProvider>
          <QueryClientProvider>
            <ProjectContextProvider>
              <IssueContextProvider>
                <Theme accentColor="purple">
                  <TimerContextProvider>{children}</TimerContextProvider>
                </Theme>
              </IssueContextProvider>
            </ProjectContextProvider>
          </QueryClientProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
